name: Build Windows App

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r desktop_app/requirements.txt
          pip install pyinstaller

      - name: Build with PyInstaller
        run: |
          pyinstaller --noconfirm --onefile --windowed --name YTCommentsApp --collect-data dateparser desktop_app/main.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: YTCommentsApp-windows
          path: |
            dist/YTCommentsApp.exe
